### ISSUE TITLE
Pull to Refresh crashes the app on iOS

### ISSUE THREAD

**Issue by m3ftah** [pandemia-app/pandemia#12]
When tested on iphone 11 with ios 13.4, the app is crashing when I do pull to refresh action on the main screen.

**Comment by Alystrasz** [comment]
We saw that this action is possible on the home view (while it shouldn't).
Is the favorites view concerned as well ?

**Comment by rouvoy** [comment]
I would expect that pulling on the favorite forces to update the current popularity charts of each favorite place.

**Comment by Alystrasz** [comment]
I agree on this, but I'd like to fix this "pull-to-refresh" unwanted (for now) feature.

**Comment by Alystrasz** [comment]
@m3ftah I feel like it's coming from the [ListView component](https://github.com/pandemia-app/pandemia/blob/master/lib/views/home.dart); setting up its `primary` and `physics` properties may fix the issue (https://api.flutter.dev/flutter/widgets/ListView-class.html).

**Comment by m3ftah** [comment]
I am closing this issue.
This issue has been resolved with #18
