### ISSUE TITLE
Adding a PWA build in the CI

### ISSUE THREAD

**Issue by rouvoy** [pandemia-app/pandemia#16]
It would be nice to include the PWA build in the CI, in addition to Android and iOS.

**Comment by m3ftah** [comment]
I have looked into this, but there are some problems.
Some of the packages we are using are not compatible with the web platform.
There are some package  replacement I can think of, but we will have to do some workarounds.
In order for a package to be web compatible, it has to have the WEB badge on the [pub.dev](https://pub.dev/flutter/packages?q=google+maps&platform=web+android+ios) hub.

<img width="1178" alt="Screenshot 2020-04-28 at 10 59 58" src="https://user-images.githubusercontent.com/3371797/80468394-69407b80-893f-11ea-85fb-4de357243da3.png">

**Comment by Alystrasz** [comment]
It seems that the flutter web ecosystem is not mature enough yet, I suggest we abandon the PWA build objective.
