### ISSUE TITLE
Adding support for heatmaps

### ISSUE THREAD

**Issue by rouvoy** [pandemia-app/pandemia#6]
Use heatmaps to reflect the popularity of a set of locations on a map, as well as the locations where I spent some time today:

- For the popularity map: The more popularity at a given time, the more red the heatmap.
- For the coverage map: The more time I spent in a location, the more red the heatmap

**Comment by Alystrasz** [comment]
Work is [still in progress for heatmaps integration](https://github.com/flutter/plugins/pull/2454#pullrequestreview-402962343) on the official google_maps_flutter package.
Shall we try to find another package?

**Comment by shreyaspapi** [comment]
Hey did you find any other package for heatmap?

**Comment by Alystrasz** [comment]
Unfortunately, nope.
I found one package that almost works though, check [my comment on the Flutter repo](https://github.com/flutter/flutter/issues/33586#issuecomment-675925673) 😃

**Comment by shreyaspapi** [comment]
Hey, thanks for a quick update!

The conversation in the issue and StackOverflow seems to have diverged and trying have a makeshift solution😁. I am still trying to find something stable to work with, will update here if I find something.

Thanks again ;)

**Comment by Alystrasz** [comment]
Here are some screenshots with different heatmaps and zoom levels (iOS to the left, Android to the right).
We can see that displayed data is the same, but there's a problem (maybe gradient size?) on iOS.

---
![Screenshot_1599483310](https://user-images.githubusercontent.com/11993538/92390973-2b890600-f11c-11ea-8896-4534c7d24f90.png)
![Screenshot_1599483430](https://user-images.githubusercontent.com/11993538/92391166-7440bf00-f11c-11ea-841e-7837017e8b82.png)
![Screenshot_1599483598](https://user-images.githubusercontent.com/11993538/92391356-cd105780-f11c-11ea-8e56-740e398a0df2.png)

**Comment by Alystrasz** [comment]
@shreyaspapi I managed to get similar rendering on Android and iOS by playing with radius, opacity, and gradient start points: https://github.com/pandemia-app/pandemia/blob/master/lib/views/places/placesState.dart#L211
